### ISSUE TITLE
Display Field in selection list

### ISSUE THREAD

**Issue by MaartenvanLoon** [pods-framework/pods#1240]
I'm not able to choose a field of a related pod to show. The direct database fields (of the related pod) I can show in the list, but not the related ones (so, these are related, to the related pod).

I'll give an example with some screenshots, because it sounds difficult like this :-)

I have a pod "employee", which had a related field to a WP user (an employee is a WP user and works for a certain company ... just one company = single select).

![Employee](https://f.cloud.github.com/assets/3957956/361440/eca59804-a1c3-11e2-9be0-0a029092eb5e.JPG)

bi-directional relationship company <--> employees (1 company --> many employees)

![Company_1](https://f.cloud.github.com/assets/3957956/361448/1f3d47ee-a1c4-11e2-9d50-66c5cfa2b793.JPG)

Now, to select/show employees for a company, I want to show fields of the WP user (like display_name or user_login)

![Company_2](https://f.cloud.github.com/assets/3957956/361466/62228d80-a1c4-11e2-87d4-04965c1fdbbf.JPG)

At this moment, on company level, I only see the emplyee ID's, which doesn't say much.

![Company_3](https://f.cloud.github.com/assets/3957956/361472/83fa979a-a1c4-11e2-90f4-a43bd099d2c7.JPG)

So, on company level, I want to show the employee with its name, which is not stored directly on "Employee" but on the "WP User".

Is that possible one way or another?

**Comment by DavidRies** [comment]
Hi, I used this patch: https://github.com/pods-framework/pods/tree/feature/1240-displayfield and it solved the following for me.

SETUP
POD A: custom post type with text field "label"
POD B: custom post type with relationship field named "group" related to POD A and the relationship field's "Display Field in Selection List" set to {@label}

CURRENT RELEASE
On the POD B edit screen, the dropdown options all said "(No Title)"

WITH THIS PATCH
On the POD B edit screen, the dropdown displayed the values of the label field as expected.

Thanks!!

**Comment by Shelob9** [comment]
fixed via #2654

**Comment by jimtrue** [comment]
This has not been fixed. This is the question about reaching across in a Relationship Field to a connected table's relationship field and showing values from THAT table.

**Comment by FLHerne** [comment]
Per 'Jim True' on Slack, after trying to use it here, this isn't actually fixed. Trying to get the string via a relationship in the target still fails.

**Comment by jimtrue** [comment]
The workaround for this one is as indicated above by @mastef 
https://github.com/pods-framework/pods/issues/1240#issuecomment-33125034

**Comment by quasel** [comment]
filter for the new DFV List View fields `pods_field_dfv_data`

**Comment by quasel** [comment]
Scenarios 
- pods_field_pick_data  -> radio / dropdown field 
workaround in this thread 
- pods_field_pick_data_ajax_items  -> search for autocomplete and list view 
workaround: #3379 
- pods_field_dfv_data -> needs research but maybe affects load etc 

as listed in #4534 each of them behaves entirely different in terms of field names or number of parameters or ... 

Why do we need a unified approach? Well for some more advanced solutions it's not always a "single" field that identifies a pod entry e.g a person can have a first and family name. Or think about bridge tables that connect multiple related pods… yes we could go and use an additional field - hello "post_title" but that feels bit weird although it solves/fixes some other WP related things ;) like Permalinks and stuff ^^

I think this could need an additional discussion as to how to deal with the post_title if it's deactivated or to maybe offer an option to set it like Display Field in selection list! 

currently it all starts here - https://github.com/pods-framework/pods/blob/edc95828c1fc94f8003d0fc8d2f3ac7bde69493b/classes/fields/pick.php#L2080 
but that's not easy to filter as it just helps preparing the query as far as I understand it :D

**Comment by JoryHogeveen** [comment]
This can be done using magic tags: `{@user_login}`.
