### ISSUE TITLE
Pods icon is missing after Pods 2.5.1 update

### ISSUE THREAD

**Issue by mj-interactive** [pods-framework/pods#2637]
Browser: Chrome Version 40.0.2214.91 (64-bit)
Mac

**Comment by Shelob9** [comment]
This issue was caused by me failing to add the new directory to WPORG svn. It is resolved via:

https://plugins.trac.wordpress.org/changeset/1073838
https://plugins.trac.wordpress.org/changeset/1073836

**Comment by mj-interactive** [comment]
Hm, it is still broken on my site. /wp-content/plugins/pods/ui/css/pods-font.css?ver=2.5.1. I did find the added font folder and the font files. But is still getting 404 error. Any thought?

**Comment by pglewis** [comment]
Could be browser caching?  Have you tried a hard refresh?

**Comment by jamesgol** [comment]
Definitely missing ui/css/pods-font.css file in the version on wordpress.org

**Comment by Shelob9** [comment]
missing pods-font.css added via:
https://plugins.trac.wordpress.org/changeset/1073864
https://plugins.trac.wordpress.org/changeset/1073863

**Comment by mj-interactive** [comment]
It's fixed! Thanks for the quick turn around!

**Comment by Shelob9** [comment]
2.5.1.1 is now available on WPORG to provide a quick fix for others affected by this.

@mj-interactive Thanks again for reporting this.
