### ISSUE TITLE
Autocomplete error when trying to search other field (not @post_title)

### ISSUE THREAD

**Issue by carherbl** [pods-framework/pods#2688]
Think it's a bug, but can't be sure. 

Pods version : 2.5.1.1
WP: 4.1

I have 2 pods stored in tables. 
From pod2 I access with a relationship (multiple, autocomplete) to pod1. I use the condition to search by one custom field, not post name:
![image](https://cloud.githubusercontent.com/assets/9322909/6066249/ff6cda28-ad6b-11e4-9eb9-ed71c923aaef.png)

and also filter the search by t.post_author = {@user.ID}

If I have only some entries in pod1 (the one where autocomplete have to search), all are listed as I click on the search box and everything is fine. 

As soon as I have more than X (I guess that from some number of entries, they are not listed automatically), I get "Searching..." and no results. 

In the admin-ajax.php:
![image](https://cloud.githubusercontent.com/assets/9322909/6066363/de24ad18-ad6c-11e4-93df-8d8a0d55d6b0.png)

I'm quite sure that the where is not well constructed, as should be d. ... not t. ...

In addition, if I change to multiselect (instead of autocomplete), everything works fine. 

Not sure if that's enough info.

**Comment by sc0ttkclark** [comment]
This may already be fixed in the upcoming Pods 2.5.2, can you try it out? http://pods.io/latest/

**Comment by carherbl** [comment]
Tried with the pods in your link, but thats 2.5.1.1? I'm seing this in the plugins page.

If your link is correct. Still getting same error.

**Comment by Shelob9** [comment]
Punting to 2.5.3

**Comment by GaryJones** [comment]
_Some time later..._

@carherbl Was this issue fixed in the recent versions of Pods?

If not could you please do an Export from Components: Migrate Packages with the minimum data needed to reproduce this?
