### ISSUE TITLE
Undefined index: input_helper

### ISSUE THREAD

**Issue by bseddon** [pods-framework/pods#2806]
Version 2.5.1.2

If I create a ui on an ACT pod using this code:

`	$object = pods( 'license' ); 

	$object->ui = array(
		'filters' => array('licencedto' ), 
		'orderby' => 't.purchasedate DESC'
	);
	pods_ui( $object );`

I see notices in my log like the one below for every member of the 'filters' array.  Is there additional information I should be supplying in this array?

`PHP Notice:  Undefined index: input_helper in ./wp-content/plugins/pods/classes/PodsUI.php on line 2580`

It doesn't seem to matter what type of field is used to filter, there is a notice for each one.

Thanks in advance.

**Comment by Shelob9** [comment]
@bseddon - You really shouldn't be using helpers any more. Why don't  you tell us what the goal of this helper is and we can help you replace it.

**Comment by sc0ttkclark** [comment]
@Shelob9 looks like a different issue

**Comment by sc0ttkclark** [comment]
https://github.com/pods-framework/pods/blob/master/classes/PodsUI.php#L2580

Field variable reference bug, need to fix `$filter_field` to make it `$options`

**Comment by Shelob9** [comment]
@sc0ttkclark Sure, but we still should get @bseddon off of helpers.

**Comment by sc0ttkclark** [comment]
He's not using helpers, it's a bug in our code that's throwing notices.

**Comment by bseddon** [comment]
<<Why don't you tell us what the goal of this helper is and we can help you replace it.>>

Sure, thanks.  The goal is to be able to generate a 'manage' page for a pod that includes additional links (additional to 'edit', 'duplicate', etc.).  In this simple case the 'actions_custom' parameter array element is not shown because the focus was to illustrate the notices.

The list being generated is a list of historical license records and I want a simple way to add an option to generate a license file in the backend.

The Pods plugin has allowed me to migrate data a load of data from an old Joomla system so it is able to co-exist in WordPress until we can finally phase it out (probably many years from now).  I've created several table-based pods and for all the others the basic manage/add/edit forms work.  Only the pod for license records needs anything else.

If there is a better way to achieve this goal it will be great to learn. I've had fun this weekend getting to grips with advanced tables and find my way around the code.  It's been a pleasure to use.  Well done.

**Comment by sc0ttkclark** [comment]
Fixed the notice in the latest http://pods.io/latest/

**Comment by bseddon** [comment]
Hi Scott, I've just applied this latest (2.5.2 beta1) but I still see the issue.  The problem I'm seeing is that $options is defined and and element 'input_helper' is added on line 2581 but then an attempt is made to access a nonexistent element 'options' on line 2581: $options[ 'options' ][ 'input_helper' ].

The three lines are:

`$options = array();
$options[ 'input_helper' ] = pods_var_raw( 'ui_input_helper', pods_var_raw( 'options', pods_var_raw( $filter, $this->fields[ 'search' ], array(), null, true ), array(), null, true ), '', null, true );
$options[ 'input_helper' ] = pods_var_raw( 'ui_input_helper', $options, $options[ 'options' ][ 'input_helper' ], null, true );`

**Comment by sc0ttkclark** [comment]
Try again, sorry I was in the middle of a few merges at once

**Comment by bseddon** [comment]
Thanks, that fixes it.
