### ISSUE TITLE
File/Image/Video field not associating files correctly

### ISSUE THREAD

**Issue by brettweaver** [pods-framework/pods#2955]
In an ACT Pod I have a field set to File/Image/Video type and it was working until today.  I ran updates yesterday and now have v2.5.2.  WordPress is at 4.2.2

Problem: When we select an image from the media library it should display a "pinkynail" image, but it doesn't. Saving a *new* record after selecting an image fails with a modal popup: "Error: Name is Empty".  Adding an image to an *existing* record seems to work, although the pinkynail is not displayed until after saving.  Before saving the record,  the url of the image is "http://icon". Doeesn't seem right, but that may not be part of the issue.  See screen shot attached.
![2015-05-20_pods-image-error](https://cloud.githubusercontent.com/assets/216288/7730130/183bcaa0-fede-11e4-8036-44ceca98e056.png)

**Comment by Shelob9** [comment]
@brettweaver Are you seeing any console errors when you set an image? A malformed AJAX response could be to blame here...

**Comment by brettweaver** [comment]
Yes re: console error:

"Failed to load resource: net::ERR_NAME_NOT_RESOLVED                   http://icon/"

![console-error](https://cloud.githubusercontent.com/assets/216288/7755028/caa6220c-ffb6-11e4-8018-a8bcc73a277b.png)

**Comment by Shelob9** [comment]
@brettweaver Yep, I see that too.

If you have a minute to test #2957 which should fix this, please let us know the results. That needs more testing before it is safe to merge.

**Comment by brettweaver** [comment]
I tried...still a little green with Git, but I replaced the contents of my ...classes/fields/file.php with the #2957 version.  The pinkynails are working, but it still won't save a record.  Screenshot shows console after attempting a save.
![name-is-empty](https://cloud.githubusercontent.com/assets/216288/7755405/64b276a0-ffb9-11e4-8d53-83ed61f90202.png)

**Comment by pglewis** [comment]
Is this verified fixed?  I've submitted a 3.0 PR as well, so is this ready to be closed?

**Comment by Shelob9** [comment]
@pglewis -- In my testing it worked. My testing was not expansive, but @sc0ttkclark said that was enough and merged it to 2.x. So close this once its merged to 3.0

**Comment by pglewis** [comment]
Merged to 3.0 so off she goes.
