### ISSUE TITLE
Underscores in pods name converted to hyphen when changing pod settings.

### ISSUE THREAD

**Issue by remcokalf** [pods-framework/pods#3499]
I have the opposite problem from this bug:
https://github.com/pods-framework/pods/issues/3095

My pod names have underscores, for example soort_boek.

Now, when I save anything in the pod's settings, it converts the underscore to a hyphen, in this example to soort-boek, breaking everything.

I upgraded to 2.6.4 from 2.6.1 when I noticed this. Could have been present already before 2.6.1, I did not change my pods a lot lately.

**Comment by sc0ttkclark** [comment]
It appears that a bug went into Pods around 2.6 that introduced this on save. In Pods 2.6.4 this was resolved. You can rename your pods back to the proper names as expected now.

**Comment by remcokalf** [comment]
Sorry, I am already using Pods 2.6.4 (with WP4.5.1). 
The issue described is still present in 2.6.4.

**Comment by jimtrue** [comment]
Verified. Created a brand new pod Test Underscores, made sure under 'Advanced' on the Create Screen, that it was `test_underscores`. When I saved the Pod, it changed to `test-underscores`. Changed the name back manually to `test_underscores` saved the Pod and it accepted the name change. Went back in and added a field, saved the Pod and the name flipped to `test-underscores`.
