### ISSUE TITLE
Getting 500 response on list view and autocomplete relationship fields

### ISSUE THREAD

**Issue by professorseo** [pods-framework/pods#6303]
### Description

I am currently unable to update websites to 2.8.3 because of the use of autocomplete and list view fields. 

I get the following error:
POST /wp-admin/admin-ajax.php?pods_ajax=1 [Response: 500]

If I manage to get inside a modal (already existing modal), the changes aren't saved. If I open a pod directly from admin.php?page=pods-manage-example, I cannot save it. 

### Version

2.8.3

### Testing Instructions

Got log. Hope it helps.

### Screenshots / Screencast

[16-Nov-2021 20:01:27 UTC] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /home/www/example/wp-content/plugins/pods/classes/fields/pick.php:2525
Stack trace:
#0 /home/www/example/wp-content/plugins/pods/classes/fields/pick.php(2525): in_array(Array, 'name', true)
#1 /home/www/example/wp-content/plugins/pods/classes/fields/pick.php(2901): PodsField_Pick->get_object_data(Array)
#2 /home/www/example/wp-includes/class-wp-hook.php(303): PodsField_Pick->admin_ajax_relationship('')
#3 /home/www/example/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /home/www/example/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /home/www/example/wp-admin/admin-ajax.php(187): do_action('wp_ajax_pods_re...')
#6 {main}
  thrown in /home/www/example/wp-content/plugins/pods/classes/fields/pick.php on line 2525

**Comment by sc0ttkclark** [comment]
It looks like your message was cut off. Is there any other detail you can provide as to what might be going on? Have you tried turning WP_DEBUG on me seeing if any error messages show on the page or in the AJAX network request?

Can you provide a package of your configuration (Pods Admin > Migrate Packages) using the Migrate Packages component (Pods Admin > Components)? That might help us to see if we can reproduce the issue.

Also helpful would be access to your Site Health information (Tools > Site Health > Info Tab > Copy site info to clipboard) would also help us determine if there are any potential conflicts from other plugins or your theme.

**Comment by sc0ttkclark** [comment]
Thanks for the email, the specific issues you reported have be resolved in the latest Pods 2.8.4 release that went out a few hours ago.

**Comment by professorseo** [comment]
The issue is partially fixed. Updating to 2.8.4 still resets some relationship fields. Single select dropdown is still working as intended, i.e. I can see the fields as they were in the previous version.

- Importing tables "_podsrel" or the actual ACT Pod from the previous version doesn't solve the issue. 
- The number of rows on _podsrel is the same on both 2.7* and 2.8.4. 
- Saving list view relationships is now possible but the modal stays open, which isn't a big deal to me, but it would most likely confuse many end users.

The help is much appreciated, Sc0ttclark!
