### ISSUE TITLE
pods_group_add is broken now

### ISSUE THREAD

**Issue by websitedesignby** [pods-framework/pods#6309]
### Description

I have used pods extensively in a project that was built in 2017. It has been working without major issues until recently.

The pod is used to extend an existing post type.

I had been hooking into the pods_meta_groups action to control the grouping of the meta-boxes.

```php
function ewas_aircraft_pod_metaboxes ( $type, $name ) { 
    
    $pod = 'ewas_aircraft';
    $context = 'normal';
    $priority = 'high';
    
    // Aircraft Images...
    $tile = 'Aircraft Images';
    $fields = array('aircraft_images');
    pods_group_add( $pod, $tile, $fields, $context, $priority);
    
    // Aircraft Info...
    $tile = 'Aircraft Info';
    $fields = array('public', 'featured', 'sold', 'manufacturer_model', 
                    'serial_number', 'serial_number_hide', 'model_year', 'registration_number',
                    'registration_number_hide', 'takeoff_gross_weight', 'landing_gross_weight', 'equipment'
                );
    pods_group_add( $pod, $tile, $fields, $context, $priority);
}

// Hook into Pods Metaboxes 
add_action( 'pods_meta_groups', 'ewas_aircraft_pod_metaboxes', 10, 2 );
```

This code now is just showing the plain custom fields and text boxes and not using the field definitions created in pods. See attached screenshot.
https://drive.google.com/file/d/13RLA0KUZkDwlQIg2dJfvKnhu1f_jOFr3/view?usp=sharing

I see I can now customize the user interface with groupings in pods and could recreate the interface that way. Unfortunately it doesn’t appear I can move existing fields into new field groups.

Any assistance would be appreciated. Let me know if more information is required.

### Version

2.8.4.1

### Screenshots / Screencast

![pods_meta_groups](https://user-images.githubusercontent.com/371860/142242292-2cc2ec2d-63f5-4cac-b78d-b0daf3299ad1.jpg)

**Comment by websitedesignby** [comment]
Hi, 

I am still having issues after testing with 2.8.5

You can recreate the issue by putting ewas-test in your plugins and importing this pods json package to build the field.
https://docs.google.com/document/d/1XB5012hTMeQYX1lpApzsN4vx1xQ4gQqoCw5uBqkud30/edit

![add_aircraft_1](https://user-images.githubusercontent.com/371860/142725493-cac69a22-351c-412d-b82f-85925d004df8.jpg)

Toggling the visibility options doesn't seem to have any effect.

![field_visibility](https://user-images.githubusercontent.com/371860/142725624-05e537bb-bfc0-4fdc-aea3-15c5b449c012.jpg)

![add_aircraft_2](https://user-images.githubusercontent.com/371860/142725645-af908924-8a7d-4559-81ca-016d41247228.jpg)

Thanks for your help.

**Comment by sc0ttkclark** [comment]
Fixed via 559bb04b4a37f08ed1c49415ff3712276e38c654 and 08ee061cf2866948d7e7d8f8c24025ba82e8e735

Please work towards utilizing the normal Pods Group feature in Pods 2.8 to manage your groups going forward as that will be the best solution long-term.

**Comment by khill07** [comment]
This is NOT totally fixed.  In the screenshots the field is an Image type field but being rendered as in the custom group as a text field.  I'm still seeing the same problem in 2.8.7.  It doesn't matter what the field type is set to, everything is rendered as a text field if added with `pods_group_add()`.
